<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Play!'
            on_press: root.manager.current = 'settings'
        Button:
            text: 'Quit'

<MemoryButton>:
    background_down: './back.png'
    done: False
    playsound: True

<LabelNarrate>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, .5
        Rectangle:
            pos: self.pos
            size: self.size

<PopupGameOver>:
